spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIEN_ID}
            client-secret: ${DISCORD_SECRER}
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - identify
              - guilds
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: username

discord:
  user-agent: Discord Bot (http://localhost:8080/)
  bot:
    token: ${BOT_TOKEN}

server:
  port: 8080